### PR TITLE
Fix python tests

### PR DESCRIPTION
**Pull request by gsmecher**
These commits tidy up a few problems in big_test.py.

The first commit uses the B("") helper to paper over what I think is a string encoding problem that goes all the way back to Python2/Python3. I have only tried this code in Python 3.12, though, so I'm reluctant to assert it wasn't introduced in a more recent python 3.x release.

The other two commits are just clean-ups for warning messages.

### CODE REVIEW

**Comment by gsmecher** [comment]
(See #3, #9)

**Comment by ketiltrout** [comment]
Hey Graeme, just to keep you up-to-date, I'm not ignoring this, but I am exploring ways of modernising the Python bindings.

**Comment by ketiltrout** [comment]
I'm still keen on re-doing the bindings in a more modern way, but until that happens, there's no reason not to accept this as-is.

**Comment by gsmecher** [comment]
Thanks - makes sense.

**Pull request merged**
